[package]
name = "explorer-storage"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
explorer-common = { path = "../explorer-common" }

async-trait.workspace = true
thiserror.workspace = true
