[package]
name = "explorer-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
anyhow.workspace = true
serde = { workspace = true }
tokio = { workspace = true }
thiserror = "1"
