[package]
name = "explorer-local-provider"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
explorer-storage.workspace = true

async-trait.workspace = true
mime_guess.workspace = true
smol.workspace = true
