[package]
name = "explorer-component"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
gpui.workspace = true

anyhow.workspace = true
rust-embed.workspace = true
serde.workspace = true
